### ISSUE TITLE
setting a base year (BASETIME) or base period for the analysis

### ISSUE THREAD

**Issue by Dubults** [markvanderloo/rtrim#13]
Dear rtrim authors,

Thanks a lot for the R version of the TRIM! Being a long-time user of the standalone TRIM, I am happy that now I will be able to do everything in R (which is my primary data analysis platform).
I would like to suggest a new feature (which I hope would not be too difficult to implement). It would be great if index() would allow the user to choose the base setting: either a single year (as implemented now) or a time period (e.g. the first 10 years of the data series) which would be used as a virtual reference against which the yearly indices are set. To put it in other words: to allow calculating the index not only dividing a total for time-point by the total for the first (or any other) time point, but also dividing a total for time-point by the mean of the totals of the specified time-points.

best wishes
Ainars Aunins
Faculty of Biology
University of Latvia

**Comment by markvanderloo** [comment]
Hi Ainar,

You can set the base year when you request the growth indices with the `index` function. Please have a look at its help fily by typing.

```r
library(rtrim)
?index
```
at the command-line. 

I will discuss your feature request here when everyone's back from their holiday :).

**Comment by Dubults** [comment]
Thanks a lot for the quick response! I am sorry for writing a request before I have explored all the other commands in detail. This morning I edited my original post so that only the request of the new feature remains.

best wishes
Ainars

**Comment by Dubults** [comment]
Dear Mark,
I assume the "time-window-based indexing" means that this new feature has been implemented starting with the 'rtrim' version 1.2. Is there any estimate when the current version will appear in CRAN or as beta version for public testing?

best wishes
Ainars

**Comment by pwbogaart** [comment]
TRIM 2.0.3 will be released soon ;-)

**Comment by pwbogaart** [comment]
rtrim 2.0.3 is on CRAN now; including time-window-based indexing, and the associated standard errors.
