### ISSUE TITLE
Model 2 with stepwise does not work

### ISSUE THREAD

**Issue by Rousettus** [markvanderloo/rtrim#14]
Hi

I have counts of Gazelle transects of 7 sites for the last 10 years.
I would like to see if there is a significant change in trend during the past 10 years. I am trying to run the following model:
z2a <- trim(count ~ site + time, data = dorcas, model = 2, changepoints = "all", stepwise = TRUE, serialcor = TRUE, overdisp = TRUE)

but I get this error:
"Error in trim_refine(count, site.id, time.id, covars, model, serialcor,  : 
  Should never happen"

other models run fine:
z3 <- trim(count ~ site + time, data = dorcas, model = 3, serialcor = TRUE, overdisp = TRUE)
z2  <- trim(count ~ site + time, data = dorcas, model = 2, serialcor = TRUE, overdisp = TRUE)

If I run the same data in the old EXE TRIM application it works fine and even shows that the year 2010 is a significant change point in the trend

I do not know what am I doing wrong.

Thank you

Asaf

attached is the file as well
[G_dorcas_count_2007till2016.xlsx](https://github.com/markvanderloo/rtrim/files/722155/G_dorcas_count_2007till2016.xlsx)

**Comment by markvanderloo** [comment]
Dear Asaf, could you provide the data for us so we can actually reproduce the error? You can send it to rtrim@cbs.nl.

Thanks,
Mark

**Comment by markvanderloo** [comment]
Thanks for the note and  the data. Behavior that differs from the original TRIM could be a bug.

**Comment by pwbogaart** [comment]
Hi Asaf,

Thanks for sharing this problem. I just found that this is caused by the first change point being removed because of the similar counts in year 1 & 2.

Apparently, this did not show up in earlier tests

We'll fix it.

Thanks, Patrick
