### ISSUE TITLE
Model with covariate returns Error in tapply(..)

### ISSUE THREAD

**Issue by popkowiersma** [markvanderloo/rtrim#15]
I've run out of ways to get a model running including a habitat covariate. I keep getting error back. If I run the model without the covariate everything goes smooth. These are some lines showing the data and commands:

> gk <- read.table("MAS_GK_09_16_temp1.csv", header=TRUE, sep=",", dec=".", na.strings=-1)
> summary(gk)
      site            time          count           Habitat     
 Min.   :  1.0    Min.   :1.00   Min.   : 0.000   Min.   :1.000  
 1st Qu.:187.0   1st Qu.:2.75   1st Qu.: 0.000   1st Qu.:1.000  
 Median :373.5   Median :4.50   Median : 0.000   Median :1.000  
 Mean   :373.5   Mean   :4.50   Mean   : 1.164   Mean   :1.623  
 3rd Qu.:560.0   3rd Qu.:6.25   3rd Qu.: 2.000   3rd Qu.:2.000  
 Max.   :746.0   Max.   :8.00   Max.   :11.290   Max.   :3.000  
> str(gk)
'data.frame':	5968 obs. of  4 variables:
 $ site   : int  1 1 1 1 1 1 1 1 2 2 ...
 $ time   : int  1 2 3 4 5 6 7 8 1 2 ...
 $ count  : num  0 0 0 0 3 1 3 2 0 0 ...
 $ Habitat: int  1 1 1 1 1 1 1 1 1 1 ...
> 
> count_summary(gk)
Total number of sites                  719
Sites without positive counts (27): 13, 17, 36, 48, 147, 162, 184, 215, 345, 366, 368, 387, 422, 423, 449, 505, 506, 532, 572, 573, 575, 576, 578, 581, 676, 745, 746
Number of observed zero counts         3081
Number of observed positive counts     2671
Total number of observed counts        5752
Number of missing counts                  0
Total number of counts                 5752
> 
> check_observations(gk, 2, covars=c("Habitat"))
$errors
list()

$sufficient
[1] TRUE

> t1 <- trim(count ~ site + time + Habitat, model=2, serialcor=TRUE, overdisp=TRUE, data=gk)
**Error in tapply(count, INDEX = index, FUN = sum, na.rm = TRUE) : 
  arguments must have same length**
_________________________________________

I've tried many different versions of csv files, altering encoding and fiddling around with the values for time and habitat variables, but to no avail. I hope someone can help solving this problem.

**Comment by GillesSanMartin** [comment]
Hello 

Same problem observed here (error message about `tapply` only when using covariates)

I think this bug appears when you have one or several sites with only 0 or NA counts.
In that case, the function `trim.estimate` have an internal procedure to remove ("kickout") these sites in the following loop : 

```
if (nkickout > 0) {
    count = count[ok]
    site.id = site.id[ok]
    time.id = time.id[ok]
    if (length(weights) > 0) 
        weights = weights[ok]
    rprintf("Removed %d %s without observations: (%s)\n", 
            nkickout, ifelse(nkickout == 1, "site", "sites"), 
            paste0(del.sites, collapse = ", "))
}
```

The problem is that these sites are removed only for the count, site.id, time and weights vectors but the covariates are ignored. Then the length of the covariates and the count is not the same anyore and this causes problem in a subsequent `tapply` call in the `get_cov_count_errlist` function.

A workaround is then to remove these sites before caling the `trim` function.


Here is an example with the attached dataset [test_data_rtrim.txt](https://github.com/markvanderloo/rtrim/files/1502781/test_data_rtrim.txt) : 

```
> m <- trim(count ~ site + year  + contexte_MAE, data = kickout(d), 
+           model = 2, serialcor = TRUE, overdisp = TRUE)
Removed 1 site without observations: (9601495)
> d <- read.csv("test_data_rtrim.csv")
> summary(d)
      site               year       contexte_MAE      count      
 Min.   :  590837   Min.   :1990   Min.   :1.00   Min.   :0.000  
 1st Qu.: 8801587   1st Qu.:1997   1st Qu.:1.00   1st Qu.:0.000  
 Median :16211796   Median :2004   Median :2.00   Median :0.000  
 Mean   :18541360   Mean   :2004   Mean   :1.64   Mean   :0.592  
 3rd Qu.:28610922   3rd Qu.:2010   3rd Qu.:2.00   3rd Qu.:1.000  
 Max.   :38166388   Max.   :2017   Max.   :2.00   Max.   :5.000  
                                                  NA's   :6032   
> 
> library(rtrim)
> m <- trim(count ~ site + year  + contexte_MAE, data = d, 
+                model = 2, serialcor = TRUE, overdisp = TRUE)
Error in tapply(count, INDEX = index, FUN = sum, na.rm = TRUE) : 
  arguments must have same length
>
```

A function to remove the problematic sites if necessary and return the cleaned dataset with a message (not extensively tested !!) : 

```
kickout <- function(x, count.id = "count", site.id = "site"){
    # for each site check if all counts are 0 or NA
    del.sites <- aggregate(x[count.id], x[site.id], function(y) {
        sum(y, na.rm = TRUE) == 0 | all(is.na(y))
    })
    # remove sites for which all counts are 0 or NA (if any)
    del.sites <- del.sites[del.sites[,2],1]
    if(length(del.sites) > 0) {
        x <- x[!x[,site.id] %in% del.sites,]
        
        # warning message
        nkickout <- length(del.sites)
        cat(sprintf("Removed %d %s without observations: (%s)\n", 
                    nkickout, ifelse(nkickout == 1, "site", "sites"), 
                    paste0(del.sites, collapse = ", ")))
    }
    return(x)
}
```

It seems to work here : 

```
> m <- trim(count ~ site + year  + contexte_MAE, data = kickout(d), 
+           model = 2, serialcor = TRUE, overdisp = TRUE)
Removed 1 site without observations: (9601495)
```

**Comment by mmthl** [comment]
Hello, 

I had the same problem and the solution provided by @GillesSanMartin seemed to work, but I got a different error after that. 

```
> count_summary(df, count.id="territories", site.id="site", time.id="year")
Total number of sites                   64
Sites without positive counts (10): 45, 46, 48, 49, 57, 179, 235, 289, 674, 2236
Number of observed zero counts          247
Number of observed positive counts      258
Total number of observed counts         505
Number of missing counts                967
Total number of counts                 1472
> m6 <- trim(territories ~ site + year + cat2, data=kickout(df),model=2,  overdisp=TRUE, autodelete=TRUE, serialcor=TRUE)
Removed 10 sites without observations: (45, 46, 48, 49, 57, 179, 235, 289, 674, 2236)
Error: min(cv) == 1 is not TRUE
In addition: Warning message:
In trim_workhorse(count, site.id, time.id, covars, model, serialcor,  :
  NAs introduced by coercion
```

Since I am quite new with both programming and TRIM, I have no idea what it means and how I can fix it.

**Comment by pwbogaart** [comment]
Thanks for all the feedback; the covariate arrays are now reduced along site/year/count arrays as well. The GitHub version (2.0.2) already is OK; a 2.0.3 will be uploaded to CRAN soon (this month)
