### ISSUE TITLE
baseline -> constant/intercept

### ISSUE THREAD

**Issue by markvanderloo** [markvanderloo/rtrim#6]
the $beta_0$ contribution is now called 'baseline'. Perhaps 'constant' (as in TRIM) or 'Intercept' (as in R) is better?

**Comment by pwbogaart** [comment]
No, beta_0 is the starting slope, active from the first time point up to the first change point (if any).
So it's not an intercept. It's also not a constant in the usual sense. Only in the 'constant slope' sense, but that has meaning only if there are no change points. So we better keep the beta_0 name.
