### ISSUE TITLE
'Empty' default settings

### ISSUE THREAD

**Issue by pwbogaart** [markvanderloo/rtrim#7]
Many TCF flags now have a default value of logical(0), which eventually behaves similar to FALSE, because isTRUE(..) is used to yield their status.

Why don't we just use a TRUE/FALSE default value? To signal that this flag ahs not been set explicitly? If that's the case, we should handle this in trim.trimconfig and convert them to TRUE/FALSE for further processing, I would suggest

**Comment by markvanderloo** [comment]
Good idea I guess. I have to update `read_tcf` anyway to include `AUTODELETE` functionality. Will have a look at this as well.

**Comment by pwbogaart** [comment]
The current approach of having all TRUE/FALSE default values (and no longer logical(0) works just fine. No reason to change it.
